# This docker-compose.yaml serves as development environment.
version: "3.8"
services:
    web:
        image: letterboxd-list-radarr:1.0
        # image: screeny05/letterboxd-list-radarr:latest
        # image: node:15.3.0-alpine3.10
        # build:
        #     context: .
        #     dockerfile: Dockerfile  # optional if named 'Dockerfile'
        ports:
            - 5543:5543
        # working_dir: /home/node/app
        # volumes:
        #     - ./:/home/node/app
        environment:
            - REDIS_URL=redis://redis:6379
            - PORT=5543
        env_file:
            - .env
        # user: node
        # command: npm run watch
        depends_on:
            - redis
    redis:
        image: redis:6.0
        command: redis-server /usr/local/etc/redis/redis.conf --appendonly yes
        volumes:
            - ./redis-data/:/data
            - ./redis.conf:/usr/local/etc/redis/redis.conf
